imports_granularity = "Crate"
fn_single_line = true
format_strings = true
match_block_trailing_comma = true
newline_style = "Unix"
wrap_comments = true
max_width = 120
group_imports = "StdExternalCrate"